hp/conversejs/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with this project. If not, see
# <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views

app_name = 'conversejs'
urlpatterns = [
    url(r'^init.js$', views.ConverseJsInitView.as_view(), name='init-js'),
    url(r'^$', views.ConverseJsView.as_view(), name='main'),
]

hp/hp/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    url(r'^%s/' % settings.ADMIN_URL.strip('/'), admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^account/', include('account.urls')),
    url(r'^feed/', include('feed.urls')),
    url(r'^chat/', include('conversejs.urls')),
    url(r'^certs/', include('certs.urls')),
    url(r'^xep0363/', include('xmpp_http_upload.urls')),
    url(r'^', include('core.urls')),
]

for route, module in settings.ADDITIONAL_URL_PATHS:
    urlpatterns.append(path('', include(module)))

# This is catch-all
urlpatterns.append(url(r'^', include('blog.urls')))

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if getattr(settings, 'ENABLE_DEBUG_TOOLBAR', False) is True:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hp/conversejs/models.py
from django.db import models  # NOQA

# Create your models here.

hp/conversejs/views.py
# -*- coding: utf-8 -*-
#
# This file is part of the jabber.at homepage (https://github.com/jabber-at/hp).
#
# This project is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This project is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with this project. If not, see
# <http://www.gnu.org/licenses/>.

import json

from django.conf import settings
from django.views.generic.base import TemplateView


class ConverseJsView(TemplateView):
    template_name = 'conversejs/main.html'


class ConverseJsInitView(TemplateView):
    template_name = 'conversejs/init.js'
    content_type = 'application/javascript'

    def get_context_data(self, *args, **kwargs):
        ctx = super(ConverseJsInitView, self).get_context_data(*args, **kwargs)
        ctx['config'] = json.dumps(settings.CONVERSEJS_CONFIG)
        ctx['setup_callback'] = settings.CONVERSEJS_SETUP_CALLBACK
        return ctx

hp/conversejs/templates/conversejs/main.html
{% extends "base.html" %}

{% load i18n static %}


{% block pagecss %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static "conversejs/converse.css" %}">
<link rel="stylesheet" type="text/css" media="screen" href="{% static "conversejs/init.css" %}">
{% endblock pagecss %}

{% block pagejs %}
<script src="{% static "conversejs/converse.js" %}"></script>
<script src="{% url "conversejs:init-js" %}"></script>
{% endblock pagejs %}

{% block title %}{% trans "Webchat" %}{% endblock title %}

{% block page %}
<div class="page-header"><h1>{% trans "Webchat" %}</h1></div>
<p>{% blocktrans %}Welcome to our still <strong>very experimental</strong> Webchat.{% endblocktrans %}</p>

{% if user.is_anonymous %}
<p>{% blocktrans with brand=site.NAME %}Use your JID (user@{{ brand }}) as XMPP username{% endblocktrans %}</p>
{% else %}
<p>{% blocktrans with jid=user %}Use your JID ({{ jid }}) as XMPP username.{% endblocktrans %}</p>
{% endif %}
{% endblock page %}